### ISSUE TITLE
Reverse the order of stack inputs for the store instructions.

### ISSUE THREAD

**Issue by fredericomba** [WebAssembly/proposals#165] opened 2023-04-18 11:33 UTC
The stack store instructions take arguments like this: `[pointer, value]`. However, if the arguments were in the order `[value, pointer]`, it would be easier to use the store instructions with long data structures on the stack. Of course, making this change would break backwards compatibility, so a "reverse" or "swap" instruction that reverses the last two values on the stack could address this.

I can't elaborate on this point right now, but if you also faced this, you'll probably know what I'm talking about.

**Comment by yfzhe** [comment] 2023-04-25 05:23
With the multi-value feature, you don't need the "reserve" or "swap" instruction but rather implement it as a function by yourself.

See: https://github.com/WebAssembly/multi-value/blob/master/proposals/multi-value/Overview.md#functions-with-multiple-return-values

**Comment by eqrion** [comment] 2023-06-16 18:38
Changes to wasm must follow this [process document](https://github.com/WebAssembly/meetings/blob/main/process/phases.md#0-pre-proposal-individual-contributor), and generally starts as an issue on the [WebAssembly/design](https://github.com/webassembly/design) repository, not in this repository.

We can't break backwards compatibility, so changing stack operand order is a non-starter. However stack manipulation instructions have been actively discussed [before](https://github.com/WebAssembly/design/issues/1381).

**Comment by tlively** [comment] 2023-06-16 19:10
I think we can close this as a duplicate of https://github.com/WebAssembly/design/issues/1381.

**Closed by tlively** 2023-06-16 19:10 UTC
